services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: playground
      TZ: Asia/Jakarta
    ports:
      - "5432:5432"

  jaeger:
    image: jaegertracing/all-in-one:1.47
    restart: unless-stopped
    ports:
      - "16686:16686"    # Jaeger UI
      - "4318:4318"      # OTLP HTTP only (for OpenTelemetry SDKs)