### Payroll
GET http://localhost:8080/payroll/

### Reimbursement
GET http://localhost:8080/reimbursement/

### Attendance
GET http://localhost:8080/attendance/

### Overtime
GET http://localhost:8080/overtime/

### Auth
GET http://localhost:8080/auth/

### Auth employee login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "employee_mjmsip",
    "password": "password123"
}

### Auth admin login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "admin_rlyo94",
    "password": "adminpass"
}

### Attendance 
POST http://localhost:8080/attendance/submit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk3Mzg4MDAsInJvbGUiOiJlbXBsb3llZSIsInN1YiI6IjU5ZGUyMjI4LWUxMzEtNDRhNC04N2Y2LWVmZWIyNjk3Zjk0NyJ9.Yv54YAkPHoxizdDKHOFwgw-3CpNou0f5wJgsoCVNlw8

### Overtime 
POST http://localhost:8080/overtime/submit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk3Mzg4MDAsInJvbGUiOiJlbXBsb3llZSIsInN1YiI6IjU5ZGUyMjI4LWUxMzEtNDRhNC04N2Y2LWVmZWIyNjk3Zjk0NyJ9.Yv54YAkPHoxizdDKHOFwgw-3CpNou0f5wJgsoCVNlw8

{
    "date": "2025-06-12",
    "hours": 2.5
}

### Payroll run
POST http://localhost:8080/payroll/run
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk3MTM3NDAsInJvbGUiOiJhZG1pbiIsInN1YiI6IjkxMjJkM2ZhLWZmYmItNGY3Zi04OGIxLTdjNGY0ZDUxYTI1YSJ9.8z9HOUNUu35bFbircr3LPNBfJjxk2zBGn4jKRMOFGco

### User
GET http://localhost:8080/user/
